<div class="table-responsive">
    <table class="table table-primary">
        <thead>

        <tr>

        <th scope="col">Name</th>
        <th scope="col">Math</th>
        <th scope="col">Englisg</th>
        <th scope="col">Urdu</th>
        <th scope="col">Biology</th>
        <th scope="col">Physics</th>
        <th scope="col">Totalmarks</th>
        <th scope="col">Obtainmark</th>
        <th scope="col">Percentage</th>
        <th scope="col">Grade</th>
        <th scope="col">Remark</th>
        </tr>
        </thead>
<tbody>
    <tr class="">

    <td scope="row"><?php echo$name?></td>
    <td scope="row"><?php echo$math?></td>
    <td scope="row"><?php echo$english?></td>
    <td scope="row"><?php echo$urdu?></td>
    <td scope="row"><?php echo$biology?></td>
    <td scope="row"><?php echo$physics?></td>
    <td scope="row"><?php echo$totalmark?></td>
    <td scope="row"><?php echo$obtain?></td>
    <td scope="row" style="color:red;"><?php echo$percentage?></td>
    <td scope="row"><?php echo$grade?></td>
    <td scope="row"><?php echo$remark?></td>
    </tr>
</tbody>
    </table>

 </div>